_BASE_: "../Base-SparseRCNN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
    TYPE_MASK: "MASK_ENCODING"
    MASK_WEIGHT: 6.0
    MASK_ENCODING:
      MASK_SIZE: 96
      DIM_MASK: 256
      PATH_ENCODING: "datasets/coco/encoding/local/encoder36_size96_dim256.pth"
      NUM_MLP: 2
      DIM_MLP: 1024
  ROI_MASK_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 14
    NUM_CONV: 4
    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
