_BASE_: "../Base-SparseRCNN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
  ROI_MASK_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 14
    NUM_CONV: 4
    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ("coco_2017_val",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (800,)

